/**
 * @file app/(landing)/about/page.tsx
 * @description About Us Page
 */

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app", // TODO: come up with description
};

const AboutPage = () => {
  return (
    <div className="container flex items-center place-content-center h-full">
      AboutPage
    </div>
  );
};

export default AboutPage;
