/**
 * @file app/(landing)/page.tsx
 * @description Landing Page
 */

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Botlhale", // TODO: Add tagline
  description: "Generated by create next app", // TODO: come up with description
};

const HomePage = () => {
  return (
    <div className="container flex items-center place-content-center h-full">
      HomePage
    </div>
  );
};

export default HomePage;
