/**
 * @file app/(landing)/auth/signIn/page.tsx
 * @description sign in page
 */

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign in | Botlhale",
  description: "Generated by create next app", // TODO: come up with description
};

const SignInPage = () => {
  return (
    <div className="container flex items-center place-content-center h-full">
      SignInPage
    </div>
  );
};

export default SignInPage;
